CREATE PROC SpImpresionBoleta
@Anho AS SMALLINT,
@Mes AS TINYINT,
@CodigoEmpleado AS VARCHAR(10)
AS
SELECT	'' AS EmpresaNombre,
		'' AS EmpresaRuc,
		'' AS EmpresaDireccion,
		'' AS MesAnho,
		'' AS EmpleadoApellidosNombres,
		'' AS EmpleadoFechaIngreso,
		'' AS EmpleadoFechaCese,
		'' AS EmpleadoAutoGenerado,
		'' AS EmpleadoCargo,
		'' AS EmpleadoFechaVacacionesSalida,
		'' AS EmpleadoFechaVacacionesRetorno,
		'' AS EmpleadoCUSPP,
		'' AS EmpleadoAFP,
		'' AS EmpleadoDNI,
		'' AS DiasLaborados,
		'' AS DiasNoLaborados,	
		'' AS DiasSinGoceHaber,	
		'' AS DiasConGoceHaber,	
		'' AS HorasNormales,
		'' AS Sueldo,	
		'' AS AsignacionFamiliar,	
		'' AS BonificacionNocturna,
		'' AS MovilidadTranslado,
		'' AS SubsidioDescansoMedico,
		'' AS BonificacionHorasExtras,
		'' AS HorasExtras,
		'' AS Cts,
		'' AS Vacaciones,
		'' AS FeriadoDominical,
		'' AS Gratificacion,
		'' AS BonificacionGratificacion,
		'' AS AfpFondo,
		'' AS AfpSeguro,
		'' AS AfpComision,
		'' AS IpssVida,
		'' AS Onp,
		'' AS Renta5Categoria,
		'' AS Inasistencias,
		'' AS InasistenciasDias,
		'' AS Adelanto,
		'' AS Tardanza,
		'' AS TardanzaMinutos,
		'' AS Gratificacion,
		'' AS RetencionJudicial,
		'' AS SeguroVida,
		'' AS IpssSalud,
		'' AS TotalBruto,
		'' AS TotalDescuentos,
		'' AS TotalApagar
FROM	TbPlanilla T0 
INNER JOIN TbPlanillaDetalle T1 ON T1.IdPlanilla = T0.IdPlanilla 
WHERE	T0.Anho = @Anho 
AND		T0.Mes = @Mes
AND		T1.CodigoEmpleado = @CodigoEmpleado