CREATE PROCEDURE SpTbPlanillaDetalleCantidadInsertar
@IdPlanillaDetalleCantidad AS INT OUTPUT,
@IdPlanilla AS INT,
@CodigoEmpleado AS VARCHAR(10),
@CantidadMinutosAsistenciaNormalDiurno AS INT,
@CantidadMinutosAsistenciaNormalDiurnoExtras1 AS INT,
@CantidadMinutosAsistenciaNormalDiurnoExtras2 AS INT,
@CantidadMinutosAsistenciaNormalNocturno AS INT,
@CantidadMinutosAsistenciaNormalNocturnoExtras1 AS INT,
@CantidadMinutosAsistenciaNormalNocturnoExtras2 AS INT,
@CantidadMinutosAsistenciaFeriadoDiurno AS INT,
@CantidadMinutosAsistenciaFeriadoDiurnoExtras1 AS INT,
@CantidadMinutosAsistenciaFeriadoDiurnoExtras2 AS INT,
@CantidadMinutosAsistenciaFeriadoNocturno AS INT,
@CantidadMinutosAsistenciaFeriadoNocturnoExtras1 AS INT,
@CantidadMinutosAsistenciaFeriadoNocturnoExtras2 AS INT,
@CantidadMinutosTardanzaNormalDiurno AS INT,
@CantidadMinutosTardanzaNormalNocturno AS INT,
@CantidadMinutosTardanzaFeriadoDiurno AS INT,
@CantidadMinutosTardanzaFeriadoNocturno AS INT,
@CantidadMinutosInasistencia AS INT
AS
BEGIN
INSERT INTO TbPlanillaDetalleCantidad (IdPlanilla,CodigoEmpleado,CantidadMinutosAsistenciaNormalDiurno,CantidadMinutosAsistenciaNormalDiurnoExtras1,CantidadMinutosAsistenciaNormalDiurnoExtras2,CantidadMinutosAsistenciaNormalNocturno,CantidadMinutosAsistenciaNormalNocturnoExtras1,CantidadMinutosAsistenciaNormalNocturnoExtras2,CantidadMinutosAsistenciaFeriadoDiurno,CantidadMinutosAsistenciaFeriadoDiurnoExtras1,CantidadMinutosAsistenciaFeriadoDiurnoExtras2,CantidadMinutosAsistenciaFeriadoNocturno,CantidadMinutosAsistenciaFeriadoNocturnoExtras1,CantidadMinutosAsistenciaFeriadoNocturnoExtras2,CantidadMinutosTardanzaNormalDiurno,CantidadMinutosTardanzaNormalNocturno,CantidadMinutosTardanzaFeriadoDiurno,CantidadMinutosTardanzaFeriadoNocturno,CantidadMinutosInasistencia)
VALUES (@IdPlanilla,@CodigoEmpleado,@CantidadMinutosAsistenciaNormalDiurno,@CantidadMinutosAsistenciaNormalDiurnoExtras1,@CantidadMinutosAsistenciaNormalDiurnoExtras2,@CantidadMinutosAsistenciaNormalNocturno,@CantidadMinutosAsistenciaNormalNocturnoExtras1,@CantidadMinutosAsistenciaNormalNocturnoExtras2,@CantidadMinutosAsistenciaFeriadoDiurno,@CantidadMinutosAsistenciaFeriadoDiurnoExtras1,@CantidadMinutosAsistenciaFeriadoDiurnoExtras2,@CantidadMinutosAsistenciaFeriadoNocturno,@CantidadMinutosAsistenciaFeriadoNocturnoExtras1,@CantidadMinutosAsistenciaFeriadoNocturnoExtras2,@CantidadMinutosTardanzaNormalDiurno,@CantidadMinutosTardanzaNormalNocturno,@CantidadMinutosTardanzaFeriadoDiurno,@CantidadMinutosTardanzaFeriadoNocturno,@CantidadMinutosInasistencia)
SET @IdPlanillaDetalleCantidad = @@IDENTITY
END