CREATE PROCEDURE [dbo].[SpTbPlanillaBoletaObtener]
@ANHO AS SMALLINT,
@MES AS TINYINT,
@CODIGOEMPLEADO AS VARCHAR(10)
AS
BEGIN
	SELECT	TOP 1 
			IdPlanillaBoleta,
			IdPlanilla,
			Anho,
			Mes,
			MesNombre,
			MesDias,
			EmpresaNombre,
			EmpresaRuc,
			EmpresaDistrito,
			EmpresaDireccion,
			EmpleadoCodigo,
			EmpleadoNombres,
			EmpleadoApellidos,
			EmpleadoCargo,
			EmpleadoNroDocumento,
			EmpleadoFechaIngreso,
			EmpleadoFechaCese,
			EmpleadoVacacionSalida,
			EmpleadoVacacionRetorno,
			EmpleadoEsSaludCodigo,
			EmpleadoSppCodigo,
			EmpleadoSppEntidad,
			DiasLaborados,
			DiasNoLaborados,
			DiasSinGoceHaber,
			DiasSubsidiado,
			HorasNormales,
			Sueldo,
			AsignacionFamiliar,
			BonificacionNocturna,
			MovilidadTranslado,
			SubsidioDescansoMedico,
			BonificacionHorasExtras,
			CantidadHorasExtras,
			Cts,
			Vacaciones,
			FeriadoDominical,
			Gratificacion,
			BonificacionGratificacion,
			TotalBruto,
			AfpFondoMonto,
			AfpSeguroMonto,
			AfpComisionMonto,
			IpssVidaMonto,
			OnpMonto,
			RentaQuintaMonto,
			InasistenciasDias,
			InasistenciasMonto,
			AdelantoMonto,
			TardanzaMinutos,
			TardanzaMonto,
			GratificacionMonto,
			RetencionJudicialMonto,
			SeguroVidaTrabajadorMonto,
			IpssSaludTrabajadorMonto,
			SeguroVidaEmpleadoMonto,
			IpssSaludEmpleadoMonto,
			TotalDescuentos,
			TotalAportes,
			TotalNeto
	FROM	TbPlanillaBoleta WITH(NOLOCK) 
	WHERE	Anho = @ANHO 
	AND		Mes = @MES 
	AND		EmpleadoCodigo = @CODIGOEMPLEADO 

END