
CREATE PROCEDURE [dbo].[SpTbVacacionReciboActualizar]
@IdVacacionRecibo AS INT,
@IdVacacion AS INT,
@Anho AS SMALLINT,
@Mes AS TINYINT,
@MesNombre AS VARCHAR(15),
@EmpresaNombre AS VARCHAR(100),
@EmpresaDistrito AS VARCHAR(150),
@EmpleadoCodigo AS VARCHAR(10),
@EmpleadoNombres AS VARCHAR(100),
@EmpleadoApellidos AS VARCHAR(100),
@EmpleadoNroDocumento AS VARCHAR(20),
@Detalle AS VARCHAR(100),
@PeriodoInicio AS DATE,
@PeriodoFinal AS DATE,
@VacacionInicio AS DATE,
@VacacionFinal AS DATE,
@Sueldo AS DECIMAL(9,2),
@AsignacionFamiliar AS DECIMAL(9,2),
@PromedioHorasExtras AS DECIMAL(9,2),
@PromedioBonificacion AS DECIMAL(9,2),
@Redondeo AS DECIMAL(9,2),
@TotalBruto AS DECIMAL(9,2),
@RetencionJudicialMonto AS DECIMAL(9,2),
@PensionEntidad AS VARCHAR(50),
@PensionMonto AS DECIMAL(9,2),
@TotalDescuento AS DECIMAL(9,2),
@TotalNeto AS DECIMAL(9,2),
@TotalNetoLiteral AS VARCHAR(255)
AS
BEGIN
UPDATE TbVacacionRecibo
SET IdVacacion = @IdVacacion,
Anho = @Anho,
Mes = @Mes,
MesNombre = @MesNombre,
EmpresaNombre = @EmpresaNombre,
EmpresaDistrito = @EmpresaDistrito,
EmpleadoCodigo = @EmpleadoCodigo,
EmpleadoNombres = @EmpleadoNombres,
EmpleadoApellidos = @EmpleadoApellidos,
EmpleadoNroDocumento = @EmpleadoNroDocumento,
Detalle = @Detalle,
PeriodoInicio = @PeriodoInicio,
PeriodoFinal = @PeriodoFinal,
VacacionInicio = @VacacionInicio,
VacacionFinal = @VacacionFinal,
Sueldo = @Sueldo,
AsignacionFamiliar = @AsignacionFamiliar,
PromedioHorasExtras = @PromedioHorasExtras,
PromedioBonificacion = @PromedioBonificacion,
Redondeo = @Redondeo,
TotalBruto = @TotalBruto,
RetencionJudicialMonto = @RetencionJudicialMonto,
PensionEntidad = @PensionEntidad,
PensionMonto = @PensionMonto,
TotalDescuento = @TotalDescuento,
TotalNeto = @TotalNeto,
TotalNetoLiteral = @TotalNetoLiteral
WHERE IdVacacionRecibo = @IdVacacionRecibo
END