CREATE PROCEDURE SpTbPlanillaBoletaInsertar
@IdPlanillaBoleta AS INT OUTPUT,
@IdPlanilla AS INT,
@Anho AS SMALLINT,
@Mes AS TINYINT,
@MesNombre AS VARCHAR(15),
@MesDias AS TINYINT,
@EmpresaNombre AS VARCHAR(100),
@EmpresaRuc AS VARCHAR(15),
@EmpresaDistrito AS VARCHAR(150),
@EmpresaDireccion AS VARCHAR(255),
@EmpleadoCodigo AS VARCHAR(10),
@EmpleadoNombres AS VARCHAR(100),
@EmpleadoApellidos AS VARCHAR(100),
@EmpleadoCargo AS VARCHAR(50),
@EmpleadoNroDocumento AS VARCHAR(20),
@EmpleadoFechaIngreso AS DATE,
@EmpleadoFechaCese AS DATE,
@EmpleadoVacacionSalida AS DATE,
@EmpleadoVacacionRetorno AS DATE,
@EmpleadoEsSaludCodigo AS VARCHAR(20),
@EmpleadoSppCodigo AS VARCHAR(20),
@EmpleadoSppEntidad AS VARCHAR(50),
@DiasLaborados AS TINYINT,
@DiasNoLaborados AS TINYINT,
@DiasSinGoceHaber AS TINYINT,
@DiasSubsidiado AS TINYINT,
@HorasNormales AS SMALLINT,
@Sueldo AS DECIMAL(10,2),
@AsignacionFamiliar AS DECIMAL(10,2),
@BonificacionNocturna AS DECIMAL(10,2),
@MovilidadTranslado AS DECIMAL(10,2),
@SubsidioDescansoMedico AS DECIMAL(10,2),
@BonificacionHorasExtras AS DECIMAL(10,2),
@CantidadHorasExtras AS SMALLINT,
@Cts AS DECIMAL(10,2),
@Vacaciones AS DECIMAL(10,2),
@FeriadoDominical AS DECIMAL(10,2),
@Gratificacion AS DECIMAL(10,2),
@BonificacionGratificacion AS DECIMAL(10,2),
@TotalBruto AS DECIMAL(10,2),
@AfpFondoMonto AS DECIMAL(10,2),
@AfpSeguroMonto AS DECIMAL(10,2),
@AfpComisionMonto AS DECIMAL(10,2),
@IpssVidaMonto AS DECIMAL(10,2),
@OnpMonto AS DECIMAL(10,2),
@RentaQuintaMonto AS DECIMAL(10,2),
@InasistenciasDias AS TINYINT,
@InasistenciasMonto AS DECIMAL(10,2),
@AdelantoMonto AS DECIMAL(10,2),
@TardanzaMinutos AS SMALLINT,
@TardanzaMonto AS DECIMAL(10,2),
@GratificacionMonto AS DECIMAL(10,2),
@RetencionJudicialMonto AS DECIMAL(10,2),
@SeguroVidaTrabajadorMonto AS DECIMAL(10,2),
@IpssSaludTrabajadorMonto AS DECIMAL(10,2),
@SeguroVidaEmpleadoMonto AS DECIMAL(10,2),
@IpssSaludEmpleadoMonto AS DECIMAL(10,2),
@TotalDescuentos AS DECIMAL(10,2),
@TotalAportes AS DECIMAL(10,2),
@TotalNeto AS DECIMAL(10,2)
AS
BEGIN
INSERT INTO TbPlanillaBoleta (IdPlanilla,Anho,Mes,MesNombre,MesDias,EmpresaNombre,EmpresaRuc,EmpresaDistrito,EmpresaDireccion,EmpleadoCodigo,EmpleadoNombres,EmpleadoApellidos,EmpleadoCargo,EmpleadoNroDocumento,EmpleadoFechaIngreso,EmpleadoFechaCese,EmpleadoVacacionSalida,EmpleadoVacacionRetorno,EmpleadoEsSaludCodigo,EmpleadoSppCodigo,EmpleadoSppEntidad,DiasLaborados,DiasNoLaborados,DiasSinGoceHaber,DiasSubsidiado,HorasNormales,Sueldo,AsignacionFamiliar,BonificacionNocturna,MovilidadTranslado,SubsidioDescansoMedico,BonificacionHorasExtras,CantidadHorasExtras,Cts,Vacaciones,FeriadoDominical,Gratificacion,BonificacionGratificacion,TotalBruto,AfpFondoMonto,AfpSeguroMonto,AfpComisionMonto,IpssVidaMonto,OnpMonto,RentaQuintaMonto,InasistenciasDias,InasistenciasMonto,AdelantoMonto,TardanzaMinutos,TardanzaMonto,GratificacionMonto,RetencionJudicialMonto,SeguroVidaTrabajadorMonto,IpssSaludTrabajadorMonto,SeguroVidaEmpleadoMonto,IpssSaludEmpleadoMonto,TotalDescuentos,TotalAportes,TotalNeto)
VALUES (@IdPlanilla,@Anho,@Mes,@MesNombre,@MesDias,@EmpresaNombre,@EmpresaRuc,@EmpresaDistrito,@EmpresaDireccion,@EmpleadoCodigo,@EmpleadoNombres,@EmpleadoApellidos,@EmpleadoCargo,@EmpleadoNroDocumento,@EmpleadoFechaIngreso,@EmpleadoFechaCese,@EmpleadoVacacionSalida,@EmpleadoVacacionRetorno,@EmpleadoEsSaludCodigo,@EmpleadoSppCodigo,@EmpleadoSppEntidad,@DiasLaborados,@DiasNoLaborados,@DiasSinGoceHaber,@DiasSubsidiado,@HorasNormales,@Sueldo,@AsignacionFamiliar,@BonificacionNocturna,@MovilidadTranslado,@SubsidioDescansoMedico,@BonificacionHorasExtras,@CantidadHorasExtras,@Cts,@Vacaciones,@FeriadoDominical,@Gratificacion,@BonificacionGratificacion,@TotalBruto,@AfpFondoMonto,@AfpSeguroMonto,@AfpComisionMonto,@IpssVidaMonto,@OnpMonto,@RentaQuintaMonto,@InasistenciasDias,@InasistenciasMonto,@AdelantoMonto,@TardanzaMinutos,@TardanzaMonto,@GratificacionMonto,@RetencionJudicialMonto,@SeguroVidaTrabajadorMonto,@IpssSaludTrabajadorMonto,@SeguroVidaEmpleadoMonto,@IpssSaludEmpleadoMonto,@TotalDescuentos,@TotalAportes,@TotalNeto)
SET @IdPlanillaBoleta = @@IDENTITY
END