CREATE TABLE [dbo].[TbPlanillaDetalle] (
    [IdPlanillaDetalle]                        INT            IDENTITY (1, 1) NOT NULL,
    [IdPlanilla]                               INT            NOT NULL,
    [CalculoPor]                               CHAR (1)       CONSTRAINT [DF_TbPlanillaDetalle_CalculoPor] DEFAULT ('M') NOT NULL,
    [CodigoEmpleado]                           VARCHAR (10)   NOT NULL,
    [IdCargo]                                  INT            NOT NULL,
    [Base]                                     DECIMAL (9, 4) NOT NULL,
    [AsignacionFamiliar]                       DECIMAL (9, 4) NOT NULL,
    [TotalBase]                                DECIMAL (9, 4) NOT NULL,
    [CantidadAsistenciaNormalDiurno]           INT            NOT NULL,
    [CostoAsistenciaNormalDiurno]              DECIMAL (9, 4) NOT NULL,
    [TotalAsistenciaNormalDiurno]              DECIMAL (9, 4) NOT NULL,
    [CantidadAsistenciaNormalDiurnoExtras1]    INT            NOT NULL,
    [CostoAsistenciaNormalDiurnoExtras1]       DECIMAL (9, 4) NOT NULL,
    [TotalAsistenciaNormalDiurnoExtras1]       DECIMAL (9, 4) NOT NULL,
    [CantidadAsistenciaNormalDiurnoExtras2]    INT            NOT NULL,
    [CostoAsistenciaNormalDiurnoExtras2]       DECIMAL (9, 4) NOT NULL,
    [TotalAsistenciaNormalDiurnoExtras2]       DECIMAL (9, 4) NOT NULL,
    [CantidadAsistenciaNormalNocturno]         INT            NOT NULL,
    [CostoAsistenciaNormalNocturno]            DECIMAL (9, 4) NOT NULL,
    [TotalAsistenciaNormalNocturno]            DECIMAL (9, 4) NOT NULL,
    [CantidadAsistenciaNormalNocturnoExtras1]  INT            NOT NULL,
    [CostoAsistenciaNormalNocturnoExtras1]     DECIMAL (9, 4) NOT NULL,
    [TotalAsistenciaNormalNocturnoExtras1]     DECIMAL (9, 4) NOT NULL,
    [CantidadAsistenciaNormalNocturnoExtras2]  INT            NOT NULL,
    [CostoAsistenciaNormalNocturnoExtras2]     DECIMAL (9, 4) NOT NULL,
    [TotalAsistenciaNormalNocturnoExtras2]     DECIMAL (9, 4) NOT NULL,
    [CantidadTardanzaNormalDiurno]             INT            NOT NULL,
    [DescuentoTardanzaNormalDiurno]            DECIMAL (9, 4) NOT NULL,
    [TotalTardanzaNormalDiurno]                DECIMAL (9, 4) NOT NULL,
    [CantidadTardanzaNormalNocturno]           INT            NOT NULL,
    [DescuentoTardanzaNormalNocturno]          DECIMAL (9, 4) NOT NULL,
    [TotalTardanzaNormalNocturno]              DECIMAL (9, 4) NOT NULL,
    [CantidadAsistenciaFeriadoDiurno]          INT            NOT NULL,
    [CostoAsistenciaFeriadoDiurno]             DECIMAL (9, 4) NOT NULL,
    [TotalAsistenciaFeriadoDiurno]             DECIMAL (9, 4) NOT NULL,
    [CantidadAsistenciaFeriadoDiurnoExtras1]   INT            NOT NULL,
    [CostoAsistenciaFeriadoDiurnoExtras1]      DECIMAL (9, 4) NOT NULL,
    [TotalAsistenciaFeriadoDiurnoExtras1]      DECIMAL (9, 4) NOT NULL,
    [CantidadAsistenciaFeriadoDiurnoExtras2]   INT            NOT NULL,
    [CostoAsistenciaFeriadoDiurnoExtras2]      DECIMAL (9, 4) NOT NULL,
    [TotalAsistenciaFeriadoDiurnoExtras2]      DECIMAL (9, 4) NOT NULL,
    [CantidadAsistenciaFeriadoNocturno]        INT            NOT NULL,
    [CostoAsistenciaFeriadoNocturno]           DECIMAL (9, 4) NOT NULL,
    [TotalAsistenciaFeriadoNocturno]           DECIMAL (9, 4) NOT NULL,
    [CantidadAsistenciaFeriadoNocturnoExtras1] INT            NOT NULL,
    [CostoAsistenciaFeriadoNocturnoExtras1]    DECIMAL (9, 4) NOT NULL,
    [TotalAsistenciaFeriadoNocturnoExtras1]    DECIMAL (9, 4) NOT NULL,
    [CantidadAsistenciaFeriadoNocturnoExtras2] INT            NOT NULL,
    [CostoAsistenciaFeriadoNocturnoExtras2]    DECIMAL (9, 4) NOT NULL,
    [TotalAsistenciaFeriadoNocturnoExtras2]    DECIMAL (9, 4) NOT NULL,
    [CantidadTardanzaFeriadoDiurno]            INT            NOT NULL,
    [DescuentoTardanzaFeriadoDiurno]           DECIMAL (9, 4) NOT NULL,
    [TotalTardanzaFeriadoDiurno]               DECIMAL (9, 4) NOT NULL,
    [CantidadTardanzaFeriadoNocturno]          INT            NOT NULL,
    [DescuentoTardanzaFeriadoNocturno]         DECIMAL (9, 4) NOT NULL,
    [TotalTardanzaFeriadoNocturno]             DECIMAL (9, 4) NOT NULL,
    [CantidadInasistencia]                     INT            NOT NULL,
    [DescuentoInasistencia]                    DECIMAL (9, 4) NOT NULL,
    [TotalInasistencia]                        DECIMAL (9, 4) NOT NULL,
    [CantidadBonoNocturnoNormal]               INT            NOT NULL,
    [TotalBonoNocturnoNormal]                  DECIMAL (9, 4) NOT NULL,
    [CantidadBonoNocturnoFeriado]              INT            NOT NULL,
    [TotalBonoNocturnoFeriado]                 DECIMAL (9, 4) NOT NULL,
    [CantidadBonoNocturno]                     INT            NOT NULL,
    [TotalBonoNocturno]                        DECIMAL (9, 4) NOT NULL,
    [CantidadBonoHorasExtrasNormal1]           INT            NOT NULL,
    [TotalBonoHorasExtrasNormal1]              DECIMAL (9, 4) NOT NULL,
    [CantidadBonoHorasExtrasNormal2]           INT            NOT NULL,
    [TotalBonoHorasExtrasNormal2]              DECIMAL (9, 4) NOT NULL,
    [CantidadBonoHorasExtrasFeriado1]          INT            NOT NULL,
    [TotalBonoHorasExtrasFeriado1]             DECIMAL (9, 4) NOT NULL,
    [CantidadBonoHorasExtrasFeriado2]          INT            NOT NULL,
    [TotalBonoHorasExtrasFeriado2]             DECIMAL (9, 4) NOT NULL,
    [CantidadBonoHorasExtras]                  INT            NOT NULL,
    [TotalBonoHorasExtras]                     DECIMAL (9, 4) NOT NULL,
    [CantidadBonoFeriadoDiurno]                INT            NOT NULL,
    [TotalBonoFeriadoDiurno]                   DECIMAL (9, 4) NOT NULL,
    [CantidadFeriadoNocturno]                  INT            NOT NULL,
    [TotalBonoFeriadoNocturno]                 DECIMAL (9, 4) NOT NULL,
    [CantidadBonoFeriado]                      INT            NOT NULL,
    [TotalBonoFeriado]                         DECIMAL (9, 4) NOT NULL,
    [TotalBono]                                DECIMAL (9, 4) NOT NULL,
    [CantidadDescuentoTardanzaNormal]          INT            NOT NULL,
    [TotalDescuentoTardanzaNormal]             DECIMAL (9, 4) NOT NULL,
    [CantidadDescuentoTardanzaFeriado]         INT            NOT NULL,
    [TotalDescuentoTardanzaFeriado]            DECIMAL (9, 4) NOT NULL,
    [CantidadDescuentoTardanza]                INT            NOT NULL,
    [TotalDescuentoTardanza]                   DECIMAL (9, 4) NOT NULL,
    [CantidadDescuentoInasistencia]            INT            NOT NULL,
    [TotalDescuentoInasistencia]               DECIMAL (9, 4) NOT NULL,
    [TotalDescuento]                           DECIMAL (9, 4) NOT NULL,
    [TotalSueldoBruto]                         DECIMAL (9, 4) NOT NULL,
    [Snp]                                      BIT            NOT NULL,
    [SnpTotal]                                 DECIMAL (9, 4) NOT NULL,
    [AfpID]                                    INT            NULL,
    [AfpTipo]                                  VARCHAR (10)   NULL,
    [AfpAporteObligatorio]                     DECIMAL (9, 4) NOT NULL,
    [AfpAporteVoluntario]                      DECIMAL (9, 4) NOT NULL,
    [AfpSeguro]                                DECIMAL (9, 4) NOT NULL,
    [AfpComision]                              DECIMAL (9, 4) NOT NULL,
    [AfpTotal]                                 DECIMAL (9, 4) NOT NULL,
    [TotalPension]                             DECIMAL (9, 4) NOT NULL,
    [TotalImpuesto]                            DECIMAL (9, 4) NOT NULL,
    [TotalSueldoNeto]                          DECIMAL (9, 4) NOT NULL,
    [RetencionJudicialPorcentual]              DECIMAL (9, 4) NOT NULL,
    [RetencionJudicialNominal]                 DECIMAL (9, 4) NOT NULL,
    [RetencionJudicialTotal]                   DECIMAL (9, 4) NOT NULL,
    [AdelantoEfectivo]                         DECIMAL (9, 4) NOT NULL,
    [AdelantoBanco]                            DECIMAL (9, 4) NOT NULL,
    [AdelantoTotal]                            DECIMAL (9, 4) NOT NULL,
    [PrestamoTotal]                            DECIMAL (9, 4) NOT NULL,
    [TotalDeduccion]                           DECIMAL (9, 4) NOT NULL,
    [TotaPago]                                 DECIMAL (9, 4) NOT NULL,
    [EsSaludTotal]                             DECIMAL (9, 4) NOT NULL,
    [MovilidadTotal]                           DECIMAL (9, 4) CONSTRAINT [DF_TbPlanillaDetalle_Movilidad] DEFAULT ((0)) NOT NULL,
    CONSTRAINT [PK_TbPlanillaDetalle] PRIMARY KEY CLUSTERED ([IdPlanillaDetalle] ASC)
);














GO
EXECUTE sp_addextendedproperty @name = N'MS_Description', @value = N'Codigo de Empleado o Colaborador', @level0type = N'SCHEMA', @level0name = N'dbo', @level1type = N'TABLE', @level1name = N'TbPlanillaDetalle', @level2type = N'COLUMN', @level2name = N'CodigoEmpleado';


GO
EXECUTE sp_addextendedproperty @name = N'MS_Description', @value = N'M = Minuto / H = Hora / D = Dia ', @level0type = N'SCHEMA', @level0name = N'dbo', @level1type = N'TABLE', @level1name = N'TbPlanillaDetalle', @level2type = N'COLUMN', @level2name = N'CalculoPor';

